POST http://localhost:8090/api/client/list?page=0&size=10
Content-Type: application/json

{
  "filtering": {
    "filterType": "ACTIVE"
  },
  "searching": "2",
  "sorting": [
    {
      "columnName": "ORDER_COUNT",
      "type": "DESC"
    },
    {
      "columnName": "ORDER_COUNT",
      "type": "ASC"
    }
  ]
}

